### PR TITLE
Navbar_styled

### PR DESCRIPTION
**Pull request by Alve2000**

### CODE REVIEW

**Review by KIET7UKE — APPROVED** [review]
Great Job !!

**Comment by KIET7UKE** [comment]
image
Don't you think there should be a text box below Pooja  perform in?

**Comment by KIET7UKE** [comment]
@Alve2000  and make a container for the navbar. keep things inside the container and make sure the container color should be highlighted.

**Comment by KIET7UKE** [comment]
@Alve2000 hello

**Comment by Alve2000** [comment]
Yes hello

**Comment by Alve2000** [comment]
> image
> Don't you think there should be a text box below Pooja  perform in? 

Yea...I'm working on it

**Pull request merged**
