### PR TITLE
Navbar_Alignment

### PR DESCRIPTION
**Pull request by Alve2000**
made small adjustments like spacing and y-axis centered alignment for login and register buttons.
previous : 
Screenshot (1443)
after :
Screenshot (1442)

### CODE REVIEW

**Comment by KIET7UKE** [comment]
@Alve2000 Do one more thing, It seems that you have forgot to add a textbox under pooja perform in line and second thing make this page responsive.

**Review by KIET7UKE — CHANGES_REQUESTED** [review]
Check PR Queries...

**Comment by Alve2000** [comment]
Okay

**Comment by Alve2000** [comment]
Check out the responsiveness for mobile devices at commit [responsive](https://github.com/KIET7UKE/BookYourPandit.com/pull/11/commits/85d3f5f791f83a5c2c9dc1e82f3dbead4eb506c6)
That's all I could do, I want some help in hiding the sidebar tho and making a drop-down list on mobile devices.

**Review by KIET7UKE — APPROVED** [review]
Good.

**Pull request merged**
